# Generated by Django 4.0.4 on 2022-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.CharField(max_length=123, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=123)),
                ('email', models.CharField(max_length=123)),
                ('name', models.CharField(max_length=123)),
                ('lecture', models.CharField(max_length=123)),
            ],
            options={
                'db_table': 'professor',
                'managed': False,
            },
        ),
    ]
